name: FLEXseg_cpu

channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults

dependencies:

  # Required for execusion
  - conda-forge::python=3.10
  - conda-forge::pip=24.0
  - conda-forge::nibabel=5.2.0
  - conda-forge::numpy=1.26.4
  - pytorch::pytorch=2.1.2
  - pytorch::cpuonly
  - pip:
    - itk==5.3.0
